# test_config.yaml
stages:
  - name: test_gsm8k_small_models
    steps:
      - name: gsm8k_small_g3_tp1
        flavor: g3
        command: >-
          export PT_HPU_LAZY_MODE=1 &&  cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 1
      - name: gsm8k_small_g3_tp2
        flavor: g3.s
        command: >-
          export PT_HPU_LAZY_MODE=1 && 
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 2
      - name: gsm8k_small_g2_tp1
        flavor: g2
        command: >-
          export PT_HPU_LAZY_MODE=1 && 
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 1
